---
language: ruby
env:
  DEVISE_SECRET_KEY_TEST: test
  GLIBRARY_USERNAME: brucellino
  GLIBRARY_PASSWORD: EQXIovD0tId4JqV4_CWGNHEzF9HYA4nk
rvm:
  - 2.2.2
install:
  - bundle install
before_script:
  - "bundle exec rake db:drop db:create db:migrate"
script:
  - bundle exec rspec spec
  - rails test
notifications:
  slack: africa-arabia-roc:qnCRTSXe8ZwiwJfIgaN0xUJN
